In [2]:
import numpy as np
import pandas as pd

# World Cup 2018
with open("./data/matches/43/3.json") as datafile:
    data = json.load(datafile)
df = pd.DataFrame(data)

In [6]:
# 全試合ぽい :cool:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           64 non-null     int64
 1   match_date         64 non-null     object
 2   kick_off           64 non-null     object
 3   competition        64 non-null     object
 4   season             64 non-null     object
 5   home_team          64 non-null     object
 6   away_team          64 non-null     object
 7   home_score         64 non-null     int64
 8   away_score         64 non-null     int64
 9   match_status       64 non-null     object
 10  match_status_360   64 non-null     object
 11  last_updated       64 non-null     object
 12  last_updated_360   64 non-null     object
 13  metadata           64 non-null     object
 14  match_week         64 non-null     int64
 15  competition_stage  64 non-null     object
 16  stadium            64 non-null     object
 17  referee            64 non-null     object
dtypes: int64(4), object(14)
memory usage: 9.1+ KB

In [7]:
df.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,7578,2018-06-15,14:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 774, 'home_team_name': 'Egypt...","{'away_team_id': 783, 'away_team_name': 'Urugu...",0,1,available,scheduled,2021-12-06T22:24:47.980215,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},1,"{'id': 10, 'name': 'Group Stage'}","{'id': 4261, 'name': ' Ekaterinburg Arena', 'c...","{'id': 287, 'name': 'Björn Kuipers', 'country'..."
1,7553,2018-06-23,17:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 791, 'home_team_name': 'South...","{'away_team_id': 794, 'away_team_name': 'Mexic...",1,2,available,scheduled,2021-12-06T23:00:56.479071,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},2,"{'id': 10, 'name': 'Group Stage'}","{'id': 256, 'name': ' Rostov Arena', 'country'...","{'id': 727, 'name': 'Milorad Mažić', 'country'..."
2,7544,2018-06-20,17:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 783, 'home_team_name': 'Urugu...","{'away_team_id': 799, 'away_team_name': 'Saudi...",1,0,available,scheduled,2021-12-06T22:50:22.229925,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},2,"{'id': 10, 'name': 'Group Stage'}","{'id': 256, 'name': ' Rostov Arena', 'country'...","{'id': 76, 'name': 'Clément Turpin', 'country'..."
3,7536,2018-06-18,17:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 782, 'home_team_name': 'Belgi...","{'away_team_id': 798, 'away_team_name': 'Panam...",3,0,available,scheduled,2021-12-06T22:40:10.487423,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},1,"{'id': 10, 'name': 'Group Stage'}","{'id': 249, 'name': ' Olimpiyskiy Stadion Fish...","{'id': 743, 'name': 'Janny Sikazwe', 'country'..."
4,7555,2018-06-24,20:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 789, 'home_team_name': 'Polan...","{'away_team_id': 769, 'away_team_name': 'Colom...",0,3,available,scheduled,2021-12-06T23:06:14.060164,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},2,"{'id': 10, 'name': 'Group Stage'}","{'id': 4258, 'name': 'Kazan'' Arena', 'country...","{'id': 740, 'name': 'César Arturo Ramos Palazu..."